plugins {
    id 'java'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

def packDir = file("${rootProject.projectDir}/../pack")

tasks.register("exportModrinth", Exec) {
    workingDir packDir
    commandLine "packwiz", "modrinth", "export"
}

tasks.register("exportCurseForge", Exec) {
    workingDir packDir
    commandLine "packwiz", "curseforge", "export"
}

tasks.register("exportAll") {
    dependsOn("exportModrinth", "exportCurseForge")
}
