name: quality

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  quality:
    permissions:
      actions: read
      contents: read
    uses: MCEnvision/.github/.github/workflows/quality.yml@2984594f1e03ee168e28c4c80701ca1e84f8cbcd
    with:
      shared-ref: "2984594f1e03ee168e28c4c80701ca1e84f8cbcd"
      native-security: true
      enforce-docs-layout: false
