name: quality

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  quality:
    permissions:
      actions: read
      contents: read
    uses: MCEnvision/.github/.github/workflows/quality.yml@e6c466f88edb57af854f597e1ce3788881d49b21
    with:
      shared-ref: "e6c466f88edb57af854f597e1ce3788881d49b21"
      native-security: true
      enforce-docs-layout: false
