name: quality

on:
  pull_request:
  push:
    branches:
      - "master"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  quality:
    permissions:
      actions: read
      contents: read
    uses: MCEnvision/.github/.github/workflows/quality.yml@8dad41905d6995e11688004f21c0a67462b9b5c0
    with:
      shared-ref: "8dad41905d6995e11688004f21c0a67462b9b5c0"
      native-security: true
      enforce-docs-layout: false
